# Generated by Django 3.1.6 on 2021-11-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0007_auto_20190204_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='note',
            field=models.TextField(max_length=1024),
        ),
    ]
