# Generated by Django 3.1.6 on 2021-11-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0008_auto_20211119_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='in_documentation',
            field=models.BooleanField(default=True),
        ),
    ]
