# Generated by Django 3.1.6 on 2021-11-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0009_testcase_in_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='in_documentation',
            field=models.BooleanField(default=False),
        ),
    ]
