# Generated by Django 3.1.6 on 2021-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_tracker', '0011_testtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtask',
            old_name='summary',
            new_name='notes',
        ),
    ]
